---
- name: Install redsocks
  apt:
    name: redsocks
  environment:
    http_proxy: "http://{{ http_proxy_host }}:{{ http_proxy_port }}"
    https_proxy: "http://{{ https_proxy_host }}:{{ https_proxy_port }}"

- name: Render redsocks configuration
  template:
    src: redsocks.conf.template
    dest: /etc/redsocks.conf

- name: Restart redsocks service
  systemd:
    enabled: yes
    name: redsocks
    state: restarted

- name: Copy iptables rules
  copy:
    src: add-iptables-rules-redsocks.txt
    dest: add-iptables-rules-redsocks.txt

- name: Apply iptables rules
  shell: iptables-restore add-iptables-rules-redsocks.txt
