---
- name: Install NFS server
  apt:
    name: nfs-kernel-server

- name: Create dir structure
  file:
    path: /srv/www/
    state: directory
    owner: nobody
    group: nogroup
    mode: o+rwx

- name: Copy configuration
  copy:
    src: exports
    dest: /etc/exports

- name: Enable and restart systemd service
  systemd:
    enabled: yes
    name: nfs-server
    state: restarted
