---
- name: Download sources
  uri:
    url: https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    dest: ./nginx-source.tgz
    creates: /nginx-source.tgz

- name: Unarchive sources
  unarchive:
    remote_src: yes
    src: ./nginx-source.tgz
    dest: ./

- name: Install build dependencies
  apt:
    name: build-essential,libpcre3,libpcre3-dev,zlib1g,zlib1g-dev,openssl,libssl-dev

- name: Configure build
  shell: ./configure --user=www-data --group=www-data --with-http_ssl_module --with-http_realip_module
  args:
    chdir: nginx-{{ nginx_version }}

- name: Build and install nginx
  make:
    chdir: nginx-{{ nginx_version }}
    target: install

- name: Copy systemd service file
  copy:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service

- name: Enable and start nginx
  systemd:
    enabled: yes
    name: nginx
    state: started
